apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-uri: ssh://fluxpres@localhost:30022/home/fluxpres/git/neoncode.git
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: neoncode
  name: neoncode
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: neoncode
  type: ClusterIP
