apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-certs
spec:
  secretName: registry-certs
  dnsNames:
    - registry.management.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
