apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - registry-deployment.yaml
  - registry-pvc.yaml
  - registry-service.yaml
secretGenerator:
  - name: htpasswd
    files:
      - htpasswd