apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    app: curl
spec:
  restartPolicy: Never
  containers:
    - name: curl-container
      #image: curlimages/curl:latest
      image: ubuntu:latest
      env:
        - name: CURL_CA_BUNDLE
          value: "/etc/ssl/certs/registry-root.pem"
      #command: ["curl", "-i", "https://registry.management.svc.cluster.local:5000"]
      command: ["sleep", "24h"]
      volumeMounts:
        - mountPath: "/etc/ssl/certs/registry-root.pem"
          subPath: "registry-root.pem"
          name: "certificates"
  volumes:
    - name: "certificates"
      secret:
        secretName: "registry-certs"
        items:
          - key: "ca.crt"
            path: "registry-root.pem"
