# See https://kind.sigs.k8s.io/docs/user/configuration/
# kind create cluster --config kind-api-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31022
    hostPort: 31022
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31090
    hostPort: 31090
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
