apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31090
      protocol: TCP
  selector:
    app: nginx-proxy
  type: NodePort
