apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      volumes:
        - name: nginx-proxy
          configMap:
            name: nginx-proxy
            items:
              - key: nginx-proxy.conf
                path: nginx.conf # Notice renaming
              - key: index.html
                path: index.html
              - key: _htpasswd
                path: .htpasswd # Notice renaming
      containers:
        - name: nginx
          image: nginx:1.25.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            #runAsUser: 0
          env:
            - name: TZ
              value: "Europe/Oslo"
          volumeMounts:
            - name: nginx-proxy
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-proxy
              mountPath: /etc/nginx/.htpasswd
              subPath: .htpasswd
              readOnly: true
            - name: nginx-proxy
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
          resources:
            requests:
              memory: "100Mi"
              cpu: "20m"
            limits:
              memory: "100Mi"
          readinessProbe:
            httpGet:
              path: '/index.html'
              port: 9090
            initialDelaySeconds: 1
            timeoutSeconds: 2
            periodSeconds: 15
      terminationGracePeriodSeconds: 0