---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-platform
  namespace: flux-cluster
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
  interval: 1m0s
  path: ./flux/platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
