apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-cluster
  namespace: backend
spec:
  interval: 0m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: nostra@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '[flux] {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./flux/tenant/backend
    strategy: Setters
