apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - ../../../base/neoncode
# - nginx.yaml
  - neoncode-imageautomation.yaml
  - image-update-automation.yaml
patches:
  - path: neoncode-patch.yaml
images:
  - name: kind-registry:5000/scienta/neon
    newName: localhost:5001/scienta/neon
