apiVersion: apps/v1
kind: Deployment
metadata:
  name: neoncode
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neoncode
  template:
    spec:
      containers:
        - name: neoncode
          #image: registry.management.svc.cluster.local:5000/scienta/neon:1.0.0-SNAPSHOT
          #image: kind-registry:5000/scienta/neon:1.0.0-SNAPSHOT
          #image: kind-registry:5001/scienta/neon:1.0.0-SNAPSHOT
          #image: neon.local.gd:5001/scienta/neon:1.0.0-SNAPSHOT
          #For Kind, it turns out that this is the image reference that works
          # image: localhost:5001/scienta/neon:1.0.3
          # Note that the host part gets rewritten by kustomize:
          image: localhost:5001/scienta/neon:1.0.0-SNAPSHOT # {"$imagepolicy": "backend:neoncode"}
          #      imagePullSecrets:
          #        - name: "image-pull-secret"
      terminationGracePeriodSeconds: 2
#          volumeMounts:
#            - mountPath: "/etc/ssl/certs/registry-root.pem"
#              subPath: "registry-root.pem"
#              name: "certificates"
#      volumes:
#        - name: "certificates"
#          secret:
#            secretName: "registry-certs"
#            items:
#              - key: "ca.crt"
#                path: "registry-root.pem"
