apiVersion: 1
contactPoints:
  - orgId: 1
    name: Slack Ops
    receivers:
      - uid: first_uid
        type: slack
        settings:
          url: SLACK
policies:
  - orgId: 1
    receiver: Slack Ops
    group_by: [
      "grafana_folder",
      "alertname"
    ]
muteTimes:
  - name: Outside office hours
    orgId: 1
    time_intervals:
      - times:
          - start_time: '00:00'
            end_time: '23:59'
  - name: Weekend
    time_intervals:
      - weekdays: ["saturday", "sunday"]
