apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - {}
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_PROXY_ENABLED
              value: "true"
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: "X-PROXY-USER"
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: "username"
            - name: GF_AUTH_PROXY_AUTO_SIGN_UP
              value: "true"
            - name: GF_AUTH_PROXY_WHITELIST
              value: "10.0.0.0/8, 127.0.0.1"
            - name: GF_AUTH_ENABLE_LOGIN_TOKEN
              value: "true"
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: access # not-in-use-as-access-is-via-proxy
            # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/
            - name: GF_SERVER_DOMAIN
              value: "grafana.local.gd"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/"
            - name: GF_SERVER_FROM_SUB_PATH
              value: "false"
