apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# It needs to set role-config for other ns: namespace: monitoring
resources:
  - ../../../base/monitoring
  - ../../../base/nginx-proxy
  # Bah included in monitoring download - ../../../base/monitoring-crd
  # - ../../../base/grafana
  - alertmanager-config.yaml
  # base/monitoring/fluxcd already contains this:
  #  - flux-prometheus-k8s-role.yaml
  #  - flux-prometheus-k8s-rolebinding.yaml
  - namespace.yaml
patches:
  - path: grafana-env-patch.yaml
#secretGenerator:
#  - name: grafana-datasources
#    files:
#      - grafana-datasources.yaml
#configMapGenerator:
#  - name: grafana-alerting
#    files:
#      - grafana-alerting.yaml
